spring:
  application:
    name: fgp-api-eureka-cluster
  config:
    activate:
      on-profile: fgp-eureka2
server:
  port: 9902
eureka:
  instance:
    hostname: fgp-eureka2
  lease-renewal-interval-in-seconds: 8
  lease-expiration-duration-in-seconds: 6
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://fgp-eureka1:9901/eureka/,http://fgp-eureka3:9903/eureka/
  server:
    renewal-threshold-update-interval-ms: 6000
    expected-client-renewal-interval-seconds: 8
