spring:
  application:
    name: fgp-api-eureka
  config:
    activate:
      on-profile: fgp-eureka3
server:
  port: 9903
  http2:
    enabled: true
  shutdown: graceful
  netty:
    max-chunk-size: 8

eureka:
  instance:
    hostname: fgp-eureka3
  lease-renewal-interval-in-seconds: 8
  lease-expiration-duration-in-seconds: 6
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://fgp-eureka1:9901/eureka/,http://fgp-eureka2:9902/eureka/
  server:
    renewal-threshold-update-interval-ms: 6000
    expected-client-renewal-interval-seconds: 8
